from pathlib import Path

FPS = 60
UNIT = 16
PACMAN_SPEED = UNIT * 10
GHOST_SPEED = UNIT * 7

HIGHSCORE_PATH = Path.home() / "pacman_highscore.txt"

PACMAN_START_POS = UNIT*14, UNIT*23
GHOST1_START_POS = UNIT*13.5, UNIT*11
GHOST2_START_POS = UNIT*12, UNIT*14
GHOST3_START_POS = UNIT*13.5, UNIT*14
GHOST4_START_POS = UNIT*15, UNIT*14

EXIT_MODE = 0
NORMAL_MODE = 1
READY_MODE = 2
DEATH_MODE = 3
ABS_DEATH_MODE = 4
ALL_PELLETS_MODE = 5

READY_INTERVAL = 1.5
DEATH_INTERVAL = 1.0
ALL_PELLETS_INTERVAL = 1.0
PACMAN_TEXTURE_SWITCH_INTERVAL = 0.1
GHOST_DIRECTION_SWITCH_INTERVAL = 0.3
POWER_PELLET_BLINK_INTERVAL = 0.15